name: Dependabot Automerge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Build & Test Feature'
    branches:
      - 'dependabot/**'

jobs:
  Test_docs-site:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Build site
          env:
            NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
            NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
          run: |
            yarn build

        - name: Jest
          env:
            JEST_JUNIT_OUTPUT_DIR: test-results/jest
            JEST_JUNIT_OUTPUT_NAME: docs-site-results.xml
          run: |
            yarn test --ci --coverage --silent --no-cache --reporters=default --reporters=jest-junit --runInBand --testResultsProcessor=jest-sonar-reporter

        - name: SonarCloud Scan
          uses: defencedigital/design-system-sonarcloud-action@master
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  Test-e2e_docs-site:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      env:
            NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
            NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Run e2e tests
          uses: cypress-io/github-action@v2
          with:
            build: yarn build
            start: yarn start

        - name: Save images for failed tests
          if: failure()
          uses: actions/upload-artifact@v2
          with:
            name: cypress_screenshots
            path: cypress/screenshots/
  Automerge:
    name: Merge Dependabot PR's
    runs-on: ubuntu-latest
    needs: [Test_docs-site, Test-e2e_docs-site]
    steps:
      - name: Auto merge Dependabot minor and patch version bumps
        uses: defencedigital/design-system-mergeme-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.MERGE_BOT }}
          PRESET: DEPENDABOT_MINOR
