name: Build & Test Master

on:
  push:
    branches:
      - master

jobs:
     Check_commits:
      runs-on: ubuntu-latest
      needs: Build_icon_library
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Attach workspace
          uses: actions/download-artifact@v2
          with:
            name: dist

        - name: check commits
          run: |
            node ./scripts/commitlint ${{ github.event.pull_request._links.html.href }}
            node ./scripts/check-fixup ${{ github.event.pull_request._links.html.href }}
