name: Build & Test Master

on:
  push:
    branches:
      - master

jobs:
    Check_commits:
      runs-on: ubuntu-latest
      needs: Build_icon_library
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Attach workspace
          uses: actions/download-artifact@v2
          with:
            name: dist

        - name: check commits
          run: |
            node ./scripts/commitlint ${{ github.event.pull_request._links.html.href }}
            node ./scripts/check-fixup ${{ github.event.pull_request._links.html.href }}
    Lint_docs-site:
      runs-on: ubuntu-latest
      env:
        ESLINT_JUNIT_OUTPUT: "test-results/eslint/docs-site-results.xml"
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Get dependencies & run lint
          run: |
            yarn install --cache-folder ~/.cache/yarn
            yarn lint:ci
    Test_docs-site:
      runs-on: ubuntu-latest
      needs: [Lint_docs-site]
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Attach workspace
          uses: actions/download-artifact@v2
          with:
            name: dist

        - name: Jest
          env:
            JEST_JUNIT_OUTPUT_DIR: test-results/jest
            JEST_JUNIT_OUTPUT_NAME: docs-site-results.xml
          run: |
            yarn test --ci --coverage --silent --no-cache --reporters=default --reporters=jest-junit --runInBand

        - name: Upload test reports to CodeCov
          run: bash <(curl -s https://codecov.io/bash)

        - name: Persist artifacts
          uses: actions/upload-artifact@v2
          with:
            name: docstest
            path: test-results/jest/docs-site-results.xml
