name: Build & Test Master

on:
  push:
    branches:
      - master

jobs:
    Security_audit:
      runs-on: ubuntu-latest
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Run audit
          run: yarn audit


    Lint_docs-site:
      runs-on: ubuntu-latest
      env:
        ESLINT_JUNIT_OUTPUT: "test-results/eslint/docs-site-results.xml"
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Get dependencies & run lint
          run: |
            yarn install --cache-folder ~/.cache/yarn
            yarn lint:ci


    Test_docs-site:
      runs-on: ubuntu-latest
      needs: [Lint_docs-site]
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Build site
          env:
            NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
            NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
          run: |
            yarn build
        - name: Jest
          env:
            JEST_JUNIT_OUTPUT_DIR: test-results/jest
            JEST_JUNIT_OUTPUT_NAME: docs-site-results.xml
          run: |
            yarn test --ci --coverage --silent --no-cache --reporters=default --reporters=jest-junit --runInBand
