name: Build & Test Feature

on: pull_request

jobs:
    Check_commits:
      runs-on: ubuntu-latest
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: check commits
          run: |
            yarn install --cache-folder ~/.cache/yarn
            node ./scripts/commitlint ${{ github.event.pull_request._links.html.href }}
            node ./scripts/check-fixup ${{ github.event.pull_request._links.html.href }}
    Security_audit:
      runs-on: ubuntu-latest
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Run audit
          run: yarn run audit

    Lint_docs-site:
      runs-on: ubuntu-latest
      env:
        ESLINT_JUNIT_OUTPUT: "test-results/eslint/docs-site-results.xml"
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Get dependencies & run lint
          run: |
            yarn install --cache-folder ~/.cache/yarn
            yarn lint:ci

    Test_docs-site:
      runs-on: ubuntu-latest
      needs: [Lint_docs-site]
      # https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
      if: ${{ github.actor != 'dependabot[bot]' }}
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Cache Node modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Switch Contentful Environment
          if: contains(github.ref, 'staging')
          run: |
            echo "NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=staging" >> $GITHUB_ENV

        - name: Build site
          env:
            NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
            NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
          run: |
            yarn build

        - name: Jest
          env:
            JEST_JUNIT_OUTPUT_DIR: test-results/jest
            JEST_JUNIT_OUTPUT_NAME: docs-site-results.xml
          run: |
            yarn test --ci --coverage --silent --no-cache --reporters=default --reporters=jest-junit --runInBand --testResultsProcessor=jest-sonar-reporter

        - name: SonarCloud Scan
          uses: defencedigital/design-system-sonarcloud-action@master
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    Test-e2e_docs-site:
      runs-on: ubuntu-latest
      needs: [Lint_docs-site]
      # https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
      if: ${{ github.actor != 'dependabot[bot]' }}
      env:
            NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
            NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2

        - name: Switch Contentful Environment
          if: contains(github.ref, 'staging')
          run: |
            echo "NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=staging" >> $GITHUB_ENV

        - name: Run e2e tests
          uses: cypress-io/github-action@v2
          with:
            build: yarn build
            start: yarn start

        - name: Save images for failed tests
          if: failure()
          uses: actions/upload-artifact@v2
          with:
            name: cypress_screenshots
            path: cypress/screenshots/
