name: Project Automation - move issues

on:
  issues:
    types: [labeled]

jobs:
  Move_labelled_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Move small/med labeled issues to Candidates column
      uses: Royal-Navy/move-labeled-or-milestoned-issue@master
      with:
        action-token: "${{ secrets.GHA_ISSUES_TOKEN }}"
        project-url: "https://github.com/Royal-Navy/docs.royalnavy.io/projects/1"
        column-name: "Candidates for Ready"
        label-name: "Size: Small, Size: Medium"
        columns-to-ignore: "Ready,In Progress,In Review,Done"
